### ISSUE TITLE
About Game's fps (macOS with GPUPassthrough) 

### ISSUE THREAD

**Issue by rkarsnk** [q-g-j/gentoo-stuff#1]
Hello, I'm rkarsnk@Japan.
I'll try to install macOS to VM on Linux/KVM(Bare:debian11) with GPUPassthrough.

Did "Middle-earth: Shadow of Mordor" you tested running on Proton(Steam for macOS)?

**Comment by q-g-j** [comment]
Hi,

no, there is a native version for macOS in Steam.

But I wouldn't use macOS for games actually - it was just for testing. Didn't run as well as in Windows after all. Same for Borderlands 2.

As far as I know, there is no proton for macOS and wine was not able to run any games that I tested. This is due to macs own graphics system (Metal).
